In [2]:
import pandas as pd

## create a dataframe views with two columns: datetime and user by reading feed- views.log

In [143]:
df = pd.read_csv('../../data/feed-views.log', sep='\t', names=['datetime', 'user'])

In [144]:
df['datetime'] = pd.to_datetime(df['datetime'])

In [145]:
df['datetime'].dtype

dtype('<M8[ns]')

In [146]:
df['year'] = df['datetime'].dt.year

In [147]:
df['month'] = df['datetime'].dt.month

In [148]:
df['day'] = df['datetime'].dt.day

In [149]:
df['hour'] = df['datetime'].dt.hour

In [150]:
df['minute'] = df['datetime'].dt.minute

In [151]:
df['second'] = df['datetime'].dt.second

In [152]:
df

,datetime,user,year,month,day,hour,minute,second
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23
2,2020-04-17 12:27:30.646665,artem,2020,4,17,12,27,30
3,2020-04-17 12:35:44.884757,artem,2020,4,17,12,35,44
4,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52
...,...,...,...,...,...,...,...,...
1071,2020-05-21 18:45:20.441142,valentina,2020,5,21,18,45,20
1072,2020-05-21 23:03:06.457819,maxim,2020,5,21,23,3,6
1073,2020-05-21 23:23:49.995349,pavel,2020,5,21,23,23,49
1074,2020-05-21 23:49:22.386789,artem,2020,5,21,23,49,22
1075,2020-05-22 10:36:14.662600,artem,2020,5,22,10,36,14

## create the new column daytime

In [153]:
# 0 – 3.59 night, 4 – 6.59 early morning, 7 – 10.59 morning, 11 – 16.59 afternoon, 17 – 19.59 early evening, 20 – 23.59 evening

In [154]:
bins = [-0.1, 3.59, 6.59, 10.59, 16.59, 19.59, 23.59]
labels = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']

In [155]:
df['time_of_day'] = df['hour'] + df['minute'] / 100

In [156]:
df

,datetime,user,year,month,day,hour,minute,second,time_of_day
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8,12.01
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23,12.01
2,2020-04-17 12:27:30.646665,artem,2020,4,17,12,27,30,12.27
3,2020-04-17 12:35:44.884757,artem,2020,4,17,12,35,44,12.35
4,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52,12.35
...,...,...,...,...,...,...,...,...,...
1071,2020-05-21 18:45:20.441142,valentina,2020,5,21,18,45,20,18.45
1072,2020-05-21 23:03:06.457819,maxim,2020,5,21,23,3,6,23.03
1073,2020-05-21 23:23:49.995349,pavel,2020,5,21,23,23,49,23.23
1074,2020-05-21 23:49:22.386789,artem,2020,5,21,23,49,22,23.49
1075,2020-05-22 10:36:14.662600,artem,2020,5,22,10,36,14,10.36

In [157]:
df['daytime'] = pd.cut(df['time_of_day'], bins=bins, labels=labels)

In [158]:
df = df.set_index('user')

In [159]:
df

,datetime,year,month,day,hour,minute,second,time_of_day,daytime
user,,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,12.01,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,12.01,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,12.27,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,12.35,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,12.35,afternoon
...,...,...,...,...,...,...,...,...,...
valentina,2020-05-21 18:45:20.441142,2020,5,21,18,45,20,18.45,early evening
maxim,2020-05-21 23:03:06.457819,2020,5,21,23,3,6,23.03,evening
pavel,2020-05-21 23:23:49.995349,2020,5,21,23,23,49,23.23,evening
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,23.49,evening
artem,2020-05-22 10:36:14.662600,2020,5,22,10,36,14,10.36,morning

## calculate the number of elements in your dataframe

In [160]:
df.count()

datetime       1076
year           1076
month          1076
day            1076
hour           1076
minute         1076
second         1076
time_of_day    1076
daytime        1076
dtype: int64

In [161]:
df['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

## sort values in your dataframe by hour, minute, and second in ascending order (simultaneously and not one by one)

In [162]:
df.sort_values(['hour', 'minute', 'second'])

,datetime,year,month,day,hour,minute,second,time_of_day,daytime
user,,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,0.00,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,0.01,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,0.01,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,0.01,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,0.01,night
...,...,...,...,...,...,...,...,...,...
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,23.49,evening
anatoliy,2020-05-09 23:53:55.599821,2020,5,9,23,53,55,23.53,evening
pavel,2020-05-09 23:54:54.260791,2020,5,9,23,54,54,23.54,evening
valentina,2020-05-14 23:58:56.754866,2020,5,14,23,58,56,23.58,evening
alexander,2020-05-14 23:59:38.758438,2020,5,14,23,59,38,23.59,evening

## calculate the minimum and maximum for the hours and the mode for the daytime categories

In [163]:
df[df['daytime'] == 'morning']['hour'].min()

8

In [164]:
df[df['daytime'] == 'night']['hour'].max()

3

In [165]:
# In addition to this, find out who visited the page at those hours (make one example from that)
df[df['hour'] == 8]

,datetime,year,month,day,hour,minute,second,time_of_day,daytime
user,,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,8.16,morning
alexander,2020-05-15 08:35:01.471463,2020,5,15,8,35,1,8.35,morning

In [166]:
df[df['hour'] == 3]

,datetime,year,month,day,hour,minute,second,time_of_day,daytime
user,,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,3.23,night
konstantin,2020-04-19 03:23:55.473926,2020,4,19,3,23,55,3.23,night
konstantin,2020-04-19 03:33:07.757714,2020,4,19,3,33,7,3.33,night

In [167]:
df['daytime'].mode()[0]

'evening'

## show the 3 earliest hours in the morning and the corresponding usernames and the 3 latest hours and the usernames using nsmallest() and nlargest()

In [1]:
df[df['daytime'] == 'morning'].nsmallest(3, columns='hour')

NameError: name 'df' is not defined

In [169]:
df[df['daytime'] == 'morning'].nlargest(3, columns='hour')

,datetime,year,month,day,hour,minute,second,time_of_day,daytime
user,,,,,,,,,
konstantin,2020-04-18 10:53:52.623447,2020,4,18,10,53,52,10.53,morning
maxim,2020-04-18 10:56:55.833899,2020,4,18,10,56,55,10.56,morning
konstantin,2020-04-18 10:57:37.331258,2020,4,18,10,57,37,10.57,morning

## use the method describe() to get the basic statistics for the columns

In [170]:
df.describe()

,datetime,year,month,day,hour,minute,second,time_of_day
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929,16.545362
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000,13.487500
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000,19.190000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000,22.092500
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000,23.590000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506,6.951277

In [171]:
iqr = 22 - 13
iqr

9